#!/usr/bin/env bash

set -eu
set -o pipefail

shopt -s extglob

PATH=$PATH:$HOME/bin

install_resources () {
  emem -r
}

build_files () {
  for file in $(ls src/!(footer.md)); do
    echo $file
    emem -Rmo "$(basename $file .md).html" $file src/footer.md
  done
}

main () {
  install_resources
  build_files
}

main $@
