#!/usr/bin/env bash

shopt -s extglob

PATH=$PATH:$HOME/bin

install_resources () {
  emem -i
}

build_files () {
  for file in $(ls src/!(footer.md)); do
    emem -n -m -o "$(basename $file .md).html" $file src/footer.md
  done
}

main () {
  install_resources
  build_files
}

main $@
